// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNiNBG_clEQVF0ABDsk4UD2MetnWZXLU4',
    appId: '1:343609024545:web:88b8ddf3706102fc30c360',
    messagingSenderId: '343609024545',
    projectId: 'flutter-berry-api',
    authDomain: 'flutter-berry-api.firebaseapp.com',
    databaseURL: 'https://flutter-berry-api-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-berry-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGxTM04KVHNXohg6kRqPU1CERtWDa6YY',
    appId: '1:343609024545:android:573dbb092874941430c360',
    messagingSenderId: '343609024545',
    projectId: 'flutter-berry-api',
    databaseURL: 'https://flutter-berry-api-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-berry-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQPKcWdn3pUrpkIV72NUqenggWPC6rPE',
    appId: '1:343609024545:ios:34af639a3ea6ccb230c360',
    messagingSenderId: '343609024545',
    projectId: 'flutter-berry-api',
    databaseURL: 'https://flutter-berry-api-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-berry-api.appspot.com',
    iosClientId: '343609024545-9h6n70vo54nv195guustsvf1clsnbikr.apps.googleusercontent.com',
    iosBundleId: 'com.example.berryCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQPKcWdn3pUrpkIV72NUqenggWPC6rPE',
    appId: '1:343609024545:ios:34af639a3ea6ccb230c360',
    messagingSenderId: '343609024545',
    projectId: 'flutter-berry-api',
    databaseURL: 'https://flutter-berry-api-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-berry-api.appspot.com',
    iosClientId: '343609024545-9h6n70vo54nv195guustsvf1clsnbikr.apps.googleusercontent.com',
    iosBundleId: 'com.example.berryCatalog',
  );
}
